=== thiagogarbazza/examples-java/example-json/src/test/resources/example-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://examples-java.com/examples-schema.json",
  "type": "object",
  "title": "The Root Schema",
  "description": "The root schema comprises the entire JSON document.",
  "required": ["codigo", "dataBase", "tipoRemessa", "empresa", "unidades"],
  "additionalProperties": false,
  "properties": {
    "codigo": {
      "$id": "#/properties/codigo",
      "type": "integer",
      "minimum": 1,
      "maximum": 9999,
      "title": "The Codigo Schema",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [1234]
    },
    "dataBase": {
      "$id": "#/properties/dataBase",
      "type": "string",
      "pattern": "^[0-9]{4}-(((0[13578]|(10|12))-(0[1-9]|[1-2][0-9]|3[0-1]))|(02-(0[1-9]|[1-2][0-9]))|((0[469]|11)-(0[1-9]|[1-2][0-9]|30)))$",
      "title": "The dataBase Schema",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": ["2019-01-31"]
    },
    "tipoRemessa": {
      "$id": "#/properties/tipoRemessa",
      "type": "string",
      "enum": ["E", "I", "S"],
      "title": "The tipoRemessa Schema",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": ["I"]
    },
    "empresa": {
      "$id": "#/properties/empresa",
      "type": "string",
      "pattern": "[A-Za-z\\d]+",
      "minLength": 3,
      "maxLength": 14,
      "title": "The Empresa Schema",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": ["12345678901234"]
    },
    "unidades": {
      "$id": "#/properties/unidades",
      "type": "array",
      "minItems": 1,
      "title": "The Unidades Schema",
      "description": "An explanation about the purpose of this instance.",
      "default": [],
      "items": {
        "$id": "#/properties/unidades/items",
        "type": "object",
        "title": "The Items Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": {},
        "examples": [
          {
            "codigo": "U1",
            "contas": [
              {
                "valor": 1234567890.01,
                "codigo": "U1-C1"
              }
            ]
          }
        ],
        "required": ["codigo", "contas"],
        "additionalProperties": false,
        "properties": {
          "codigo": {
            "$id": "#/properties/unidades/items/properties/codigo",
            "type": "string",
            "pattern": "U([\\d])+",
            "title": "The Codigo Schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": ["U1"]
          },
          "contas": {
            "$id": "#/properties/unidades/items/properties/contas",
            "type": "array",
            "minItems": 1,
            "title": "The Contas Schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "items": {
              "$id": "#/properties/unidades/items/properties/contas/items",
              "type": "object",
              "title": "The Items Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": {},
              "examples": [
                {
                  "valor": 1234567890.01,
                  "codigo": "U1-C1"
                }
              ],
              "required": ["codigo", "valor"],
              "additionalProperties": false,
              "properties": {
                "codigo": {
                  "$id": "#/properties/unidades/items/properties/contas/items/properties/codigo",
                  "type": "string",
                  "pattern": "U([\\d])+-C([\\d])+",
                  "title": "The Codigo Schema",
                  "description": "An explanation about the purpose of this instance.",
                  "default": "",
                  "examples": ["U1-C1"]
                },
                "valor": {
                  "$id": "#/properties/unidades/items/properties/contas/items/properties/valor",
                  "type": "number",
                  "title": "The Valor Schema",
                  "description": "An explanation about the purpose of this instance.",
                  "default": "",
                  "examples": [1234567890.01]
                }
              }
            }
          }
        }
      }
    }
  }
}

=== thiagogarbazza/examples-java/example-json/src/test/resources/example-valid/example-valid-02.json
{
  "codigo": 1234,
  "dataBase": "2019-01-31",
  "tipoRemessa": "I",
  "empresa": "12345678901234",
  "unidades": [
    {
      "codigo": "U1",
      "contas": [
        {
          "codigo": "U1-C1",
          "valor": 1234567890.01
        },
        {
          "codigo": "U1-C2",
          "valor": 1234567890.01
        }
      ]
    },
    {
      "codigo": "U2",
      "contas": [
        {
          "codigo": "U2-C1",
          "valor": 1234567890.01
        },
        {
          "codigo": "U2-C2",
          "valor": 1234567890.01
        }
      ]
    }
  ]
}
